### PR TITLE
cmake support, build on circleci, travisci.  readme.

### PR DESCRIPTION
**Pull request by tesch1**
Hi,
Thanks for the nice library!  Here's some support files to build using cmake, and run builds automatically on circleci (ie https://circleci.com/gh/tesch1/svg_plot).  The tests dont build yet.  I'm more than happy to make any other cleanups if you like.
Cheers,
Michael

### CODE REVIEW

**Comment by pabristow** [comment]
Glad to see that you are finding this useful.  As you note, it is a bit dated, and far too buggy :-( I am part way through a major update which will of course include using C++11 and later.  However I have got part way through and I am distracted with other more pressing tasks.  I have yet to find a good way of testing because looking at the plots seems to be the only reliable way of telling if it is working correctly.

But I will have a look at what you propose and may either pull these changes or perhaps pull onto a branch so that people who are using the current C++03-compatible version can continue to use it as is.

It wil valuable to have a CMake build (though I don't use CMake, it seems to be the build-du-jour.)

Many thanks for your work on this sadly neglected project.

**Comment by tesch1** [comment]
Thanks for the quick answer, and thanks again for making this library available (even if it's dated a bit).  We need some simple plots, so are pretty motivated to make things work right, and I'd much rather do that in the "plays nice with others" way than go off with an incompatible branch.  C++ with SVG is super interesting now that WASM works pretty well.

I played a little with the 'develop' branch but noticed that it was in a non-working state.  What about creating an intermediate c++11(14/17?) branch that might break features from master, but is always in a working/building state?  Is there a task-list for your rewrite we could help with?

For testing, maybe outputting a non-compressed binary form of the image (tiff,bmp) and just bit-comparing it against a gold version?  That way changes can be flagged and inspected visually -- if the changes are desired, then the gold reference file can be updated.  It's not perfect, but at least it will catch unwanted unexpected side-effects of changes.

As a side note - how do you feel about removing boost dependency?  (and pulling `quan` into the repo)  Boost is a 90 MB download, and I suspect most of the functionality that's being used (I'm not far enough along to be completely sure of this) could be expressed pretty simply in a little utility library.

**Comment by pabristow** [comment]
I fear that Boost is deeply embedded - and anyway, you are using Boost already aren't you ;-)

Quan is especially useful to provide the handling of uncertainty in the input data values so that the plus-and-minus shows nicely.

I've tried a bit-compare but there are far too many differences in the SVG from tiny changes to the C++ code that lead to many false-positives making it pretty useless as a test.  Eyeballing is the real test, and is tedious.

Develop is in a major mess at present, and I don't have time to work on it at present (Boost.Math is my priority).  But I'll try to decide the best way forward.

**Comment by tesch1** [comment]
Oh, I didn't mean to get rid of quan, just to pull it into this repo.

No, we're not using boost, but would (reluctantly) have to in order to use this library.  We hadn't joined the boost bloat cult yet.  Perhaps relatedly, the example binaries are enormous ;o)

Let me know if we can help - in the meantime we'll go down a hopefully compatible path of cmake and minimal dependencies and such...

**Review by pabristow — COMMENTED** [review]
I would hope than one can make this NOT Boost version specific
URL "https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.bz2"
but not being a CMake user I don't know how to do this.

I am concerned that some of the replacements to use std:: rather than boost:: may not have the same effect as std:: .  boost::math::tools::max_value<FPT>(), for example, covers more floating-point types, including Boost.Multiprecision, fixed_point etc and may be unwise/unhelpful.  Most of the boost version fall thru to std:: if it is available, so changes would this plot package unusable for those still stuck in the Dark Ages of C++03, and to no benefit to others.  Unless you can eliminate every last use of boost, you will have to be able to *include* the Boost libraries header-only files.  There will be little or no increase in binary size by using Boost. It is not necessary to build and link to Boost.Test .lib files - you can use the /included versions.  I would not try to run any tests - they are pretty much useless in my experience - I don't run them - I just scan the plots that I get to check they look right - or preferably "righter" ;-).  

(Probably needless to say, I am a Visual Studio user, and would use Boost's bjam/b2 build system if I can needing to, but normally stuck to VS entirely).  One is only interested in the pretty plots SVG files inthe end).

So I can't approve such changes because of their downsides for current users.  A separate branch would be fine with me.

**Comment by tesch1** [comment]
The version of boost can just be changed in the string, I suppose, for example, if one wanted to test across a range of commonly available boost versions (assuming the automated testing was usable).  I didn't see any reason to make it configurable, since it only gets used if the user doesn't have boost installed anyway.

I can back out the boost:: -> std:: changes, I got a little carried away on that, should have kept those in a separate branch.

**Comment by pabristow** [comment]
I'm really committed to using Boost (headers only) for many reasons, so I think that reverting the std:: changes would be best.

I am not a *nix user.  Is it difficult to install Boost header files (without all the prebuilt libraries)?  They take up space on the users disk, but have little other cost (and massive benefits).  (I have encountered resistance to using Boost from people who expect lots of .lib or .dll files, but part of Boost strength is that nearly everything can be used header-only).

**Comment by tesch1** [comment]
I'm the polar opposite - haven't used windows since the 00s, and then (ironically) only for email :o)

It's not that it's difficult for an individual user to install boost, it's just that it's different for everyone.  CMake provides some nice features for finding or downloading that are cross-platform.  So the strategy is to first search for a boost installation (using cmake's find_package) and if that doesn't find anything, then just download a (known-compatible) copy of boost using cmake, which is pretty much guaranteed to work on "all of the things" (except apparently the windows things.. for some reason testing doesn't work on win32... I dont have a good way to debug it though)  https://travis-ci.com/tesch1/svg_plot/builds 

Added some demo images and link to the documentation.

**Pull request closed without merging**
