### PR TITLE
Add static_cast so that types other than double and float are support…

### PR DESCRIPTION
**Pull request by jzmaddock**
…ed (long double etc).

### CODE REVIEW

**Review by pabristow — COMMENTED** [review]
I have adopted this adding a static check for convertible to double, so one gets a good message, for example when using cpp_bin_float_quad which would be hideously inefficient with std::map.

i:\modular-boost\boost\svg_plot\detail\functors.hpp(207): error C2338: Uncertain types must be convertible to double!

       // Cast to double so that can use with float, long double.
      BOOST_STATIC_ASSERT_MSG(std::is_convertible<T, double>::value, "Uncertain types must be convertible to double!");
      BOOST_STATIC_ASSERT_MSG(std::is_convertible<U, double>::value, "Uncertain types must be convertible to double!");
      return std::pair<Meas, unc<correlated> >((Meas)(a.first), (unc<correlated>)(static_cast<double>(a.second)));
a

Does this sound sensible?

Thanks.

**Comment by jzmaddock** [comment]
Doesn't work (I think anyway) - cpp_bin_float_quad for example is *not* convertible to double.  However, is_constructible<double, T>::value would be fine, since there is an explicit conversion (hence the need for a static_cast).

**Comment by pabristow** [comment]
Correct, is_constructible works even for cpp_bin_float_quad (and even int - though using constant pi in generating test data make pi = 3, as approved by https://en.wikipedia.org/wiki/Indiana_Pi_Bill US in 1897 !).
Needed several more static_casts.  Will commit on develop branch.

**Comment by pabristow** [comment]
Correct, is_constructible works even for cpp_bin_float_quad (and even int - though using constant pi in generating test data make pi = 3, as approved by https://en.wikipedia.org/wiki/Indiana_Pi_Bill US in 1897 !).
Needed several more static_casts.  Will commit on develop branch.

**Pull request closed without merging**
